name: Update README

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mian.py'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update README with latest info
      run: |
        # 获取最新的镜像信息
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # 更新 README 中的镜像地址
        sed -i "s|ghcr\.io/[^:]*:|ghcr.io/$REPO_LOWER:|g" README.md
        
        # 添加构建状态徽章（如果还没有的话）
        if ! grep -q "github/workflows/docker-build" README.md; then
          sed -i '1i[![Docker Build](https://github.com/${{ github.repository }}/actions/workflows/docker-build.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/docker-build.yml)\n' README.md
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "docs: 自动更新 README 中的镜像地址"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}